SUPABASE_URL="https://jxjfqwtnxxvdcgzfrwoo.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4amZxd3RueHh2ZGNnemZyd29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0MTgwNTIsImV4cCI6MjEwMDk5NDA1Mn0.4gSjUVp-Ly6uSXzd-QZSXYpG-PalH9YZDe0pRK71THY"
SUPABASE_SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4amZxd3RueHh2ZGNnemZyd29vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTQxODA1MiwiZXhwIjoyMTAwOTk0MDUyfQ.ZU0b8El9DfiXNQrxrmf49lggH-YJltEkIGhjPojwkMY"
R2_BUCKET_NAME="kalam"
R2_ACCOUNT_ID="26b2e1d76ead46ae8a1efad2fbc6f4cb"
R2_ACCESS_KEY_ID="2721ebeb3dcbe4766bf0e8bbf8191c69"
R2_SECRET_ACCESS_KEY="20c913584d78369000129b440da17d0dfd775a5ad1ac0b7bd84aa639feee8ee6"
R2_PUBLIC_BASE_URL="https://pub-4ef637e0a95f4fe88fc0dacd69c3602a.r2.dev"
COOKIES_PASSWORD="number.nine123"
OLLAMA_API="25d4a18262384bad95d07405889ef9c7.oUSdnY6SCN4nMe8EmnElGC-S"
ELEVENLABS_KEY="sk_f039e1686cd1e91577823a41b3fe8cefb631414d0a199c1b"